import React from 'react';
import { Icons } from './Icons';

export default { title: 'Atoms|Icons' };

export const ANT: React.FC = () => <Icons name="ANT" />;
export const DAPPER: React.FC = () => <Icons name="DAPPER" />;
export const BAT: React.FC = () => <Icons name="BAT" />;
export const DAI: React.FC = () => <Icons name="DAI" />;
export const ENG: React.FC = () => <Icons name="ENG" />;
export const KNC: React.FC = () => <Icons name="KNC" />;
export const MKR: React.FC = () => <Icons name="MKR" />;
export const LINK: React.FC = () => <Icons name="LINK" />;
export const MANA: React.FC = () => <Icons name="MANA" />;
export const OMG: React.FC = () => <Icons name="OMG" />;
export const REN: React.FC = () => <Icons name="REN" />;
export const RLC: React.FC = () => <Icons name="RLC" />;
export const SAI: React.FC = () => <Icons name="SAI" />;
export const USDC: React.FC = () => <Icons name="USDC" />;
export const USDT: React.FC = () => <Icons name="USDT" />;
export const MLN: React.FC = () => <Icons name="MLN" />;
export const REP: React.FC = () => <Icons name="REP" />;
export const WBTC: React.FC = () => <Icons name="WBTC" />;
export const WETH: React.FC = () => <Icons name="WETH" />;
export const ZRX: React.FC = () => <Icons name="ZRX" />;
export const DGX: React.FC = () => <Icons name="DGX" />;
export const EUR: React.FC = () => <Icons name="EUR" />;
export const METAMASK: React.FC = () => <Icons name="METAMASK" />;
export const FRAME: React.FC = () => <Icons name="FRAME" />;
export const GANACHE: React.FC = () => <Icons name="GANACHE" />;
export const TWITTER: React.FC = () => <Icons name="TWITTER" />;
export const LEFTARROW: React.FC = () => <Icons name="LEFTARROW" />;
export const SWAPARROWS: React.FC = () => <Icons name="SWAPARROWS" />;
export const EXCHANGE: React.FC = () => <Icons name="EXCHANGE" />;
export const FORTMATIC: React.FC = () => <Icons name="FORTMATIC" />;
export const SUN: React.FC = () => <Icons name="SUN" />;
export const MOON: React.FC = () => <Icons name="MOON" />;
